NXNMhPIR/2486-how-to-provide-mock-data-to-the-provider
notificationapi-com/notificationapi-react-client-sdk pull request #16
Opened 2024-10-16 16:35 UTC by mbasadi

2024-10-16 20:35 UTC, sahandseifi requested changes
There should be a mock mode where websocket, API calls, etc are not made.

Please review everywhere we mock the sdk in our front-end and ensure this can accomplish the same.

2024-10-17 14:39 UTC, mbasadi commented
> There should be a mock mode where websocket, API calls, etc are not made.
> 
> Please review everywhere we mock the sdk in our front-end and ensure this can accomplish the same.

No network call during the mocked mode

2024-10-17 15:15 UTC, mbasadi commented on lib/components/Provider/index.tsx
> +        if (config.connectionMode === 'live') {
similar to https://github.com/notificationapi-com/notificationapi-js-client-sdk/blob/bb982a9aa2234453c4d379ee312d242abbab231d/src/index.ts#L247

2024-10-17 19:28 UTC, sahandseifi requested changes
This PR does not address the requirements of the relevant tasks. Please review the requirements and re-implement.

2024-10-17 19:28 UTC, sahandseifi commented on lib/components/Provider/index.tsx
> +  connectionMode?: 'live' | 'mocked';
Please pick a better term. The mode is not about the connection (e.g. HTTP vs HTTPS), it's about the whole component and how it operates.

2024-10-17 19:28 UTC, sahandseifi commented on lib/components/Provider/index.tsx
> +    if (config.connectionMode === 'live')
Please research other tools to see if it's possible to do this in a nicer way, so we don't have to use if/else for every network call.

2024-10-22 21:36 UTC, closed without merging